version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 2
  reviewers:
  - benjello
  ignore:
  - dependency-name: autopep8
    versions:
    - 1.5.6
  - dependency-name: numpy
    versions:
    - 1.19.0
    - 1.20.0
