repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1 # Use the version of ruff you have installed or a recent one
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format