###############################################################################
## File describing the package for Anaconda.org
## Warning! PYPI_VERSION, PYPI_URL and PYPI_SHA256 strings are replaced
## by the CI. They must be kept as they are.
## It uses Jinja2 templating code to retreive information from setup.py
###############################################################################

{% set name = "OpenFisca-Survey-Manager" %}
{% set data = load_setup_py_data() %}
{% set version = "PYPI_VERSION" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# openfisca-survey-manager package source
source:
  url: PYPI_URL
  sha256: PYPI_SHA256

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    {% for req in data.get('install_requires', []) %}
    - {{ req }}
    {% endfor %}


test:
  imports:
    - openfisca_survey_manager
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: openfisca-survey-manager

  - name: openfisca-survey-manager-matching
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - feather
        - rpy2
        - {{ pin_subpackage('openfisca-survey-manager', exact=True) }}

  - name: openfisca-survey-manager-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - autopep8 >=1.4.0,<=1.5.7
        - coveralls >=1.5.0,<3.4.0
        - flake8 >=3.8.0,<3.10.0
        - openfisca-country-template >=3.6.0,<4.0.0
        - pytest >=4.0.0,<7.0.0
        - pytest-cov >=2.0.0, <3.0.0
        - scipy >=1.2.1, <2.0.0
        - {{ pin_subpackage('openfisca-survey-manager', exact=True) }}

  - name: openfisca-survey-manager-sas
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - pyreadstat >=1.1.4, <2.0.0
        - SAS7BDAT >=2.2.2, <3.0.0
        - {{ pin_subpackage('openfisca-survey-manager', exact=True) }}

about:
  home: https://fr.openfisca.org/
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE.AGPL.txt
  summary: "Survey-Manager module, to work with OpenFisca and survey data."
  description: |
    OpenFisca is a versatile microsimulation free software.
    This repository contains the Survey-Manager module, to work with OpenFisca and survey data.
  doc_url: https://fr.openfisca.org/
  dev_url: https://github.com/openfisca/openfisca-survey-manager/
